package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * Accesorio generated by hbm2java
 */
public class Accesorio  implements java.io.Serializable {


     private Integer idAccesorio;
     private int productoIdProducto;
     private String nombre;

    public Accesorio() {
    }

    public Accesorio(int productoIdProducto, String nombre) {
       this.productoIdProducto = productoIdProducto;
       this.nombre = nombre;
    }
   
    public Integer getIdAccesorio() {
        return this.idAccesorio;
    }
    
    public void setIdAccesorio(Integer idAccesorio) {
        this.idAccesorio = idAccesorio;
    }
    public int getProductoIdProducto() {
        return this.productoIdProducto;
    }
    
    public void setProductoIdProducto(int productoIdProducto) {
        this.productoIdProducto = productoIdProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


