package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * CarroComprasHasProductoId generated by hbm2java
 */
public class CarroComprasHasProductoId  implements java.io.Serializable {


     private int carroComprasIdCarroCompras;
     private int productoIdProducto;

    public CarroComprasHasProductoId() {
    }

    public CarroComprasHasProductoId(int carroComprasIdCarroCompras, int productoIdProducto) {
       this.carroComprasIdCarroCompras = carroComprasIdCarroCompras;
       this.productoIdProducto = productoIdProducto;
    }
   
    public int getCarroComprasIdCarroCompras() {
        return this.carroComprasIdCarroCompras;
    }
    
    public void setCarroComprasIdCarroCompras(int carroComprasIdCarroCompras) {
        this.carroComprasIdCarroCompras = carroComprasIdCarroCompras;
    }
    public int getProductoIdProducto() {
        return this.productoIdProducto;
    }
    
    public void setProductoIdProducto(int productoIdProducto) {
        this.productoIdProducto = productoIdProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CarroComprasHasProductoId) ) return false;
		 CarroComprasHasProductoId castOther = ( CarroComprasHasProductoId ) other; 
         
		 return (this.getCarroComprasIdCarroCompras()==castOther.getCarroComprasIdCarroCompras())
 && (this.getProductoIdProducto()==castOther.getProductoIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCarroComprasIdCarroCompras();
         result = 37 * result + this.getProductoIdProducto();
         return result;
   }   


}


