package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * CarroComprasHasProducto generated by hbm2java
 */
public class CarroComprasHasProducto  implements java.io.Serializable {


     private CarroComprasHasProductoId id;

    public CarroComprasHasProducto() {
    }

    public CarroComprasHasProducto(CarroComprasHasProductoId id) {
       this.id = id;
    }
   
    public CarroComprasHasProductoId getId() {
        return this.id;
    }
    
    public void setId(CarroComprasHasProductoId id) {
        this.id = id;
    }




}


