package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * CarroCompras generated by hbm2java
 */
public class CarroCompras  implements java.io.Serializable {


     private Integer idCarroCompras;
     private int pedidoIdPedido;
     private int usuarioIdUsuario;

    public CarroCompras() {
    }

    public CarroCompras(int pedidoIdPedido, int usuarioIdUsuario) {
       this.pedidoIdPedido = pedidoIdPedido;
       this.usuarioIdUsuario = usuarioIdUsuario;
    }
   
    public Integer getIdCarroCompras() {
        return this.idCarroCompras;
    }
    
    public void setIdCarroCompras(Integer idCarroCompras) {
        this.idCarroCompras = idCarroCompras;
    }
    public int getPedidoIdPedido() {
        return this.pedidoIdPedido;
    }
    
    public void setPedidoIdPedido(int pedidoIdPedido) {
        this.pedidoIdPedido = pedidoIdPedido;
    }
    public int getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(int usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }




}


