package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * CatalogoHasVehiculo generated by hbm2java
 */
public class CatalogoHasVehiculo  implements java.io.Serializable {


     private CatalogoHasVehiculoId id;

    public CatalogoHasVehiculo() {
    }

    public CatalogoHasVehiculo(CatalogoHasVehiculoId id) {
       this.id = id;
    }
   
    public CatalogoHasVehiculoId getId() {
        return this.id;
    }
    
    public void setId(CatalogoHasVehiculoId id) {
        this.id = id;
    }




}


