package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * CatalogoHasVehiculoId generated by hbm2java
 */
public class CatalogoHasVehiculoId  implements java.io.Serializable {


     private int catalogoIdCatalogo;
     private int vehiculoIdVehiculo;

    public CatalogoHasVehiculoId() {
    }

    public CatalogoHasVehiculoId(int catalogoIdCatalogo, int vehiculoIdVehiculo) {
       this.catalogoIdCatalogo = catalogoIdCatalogo;
       this.vehiculoIdVehiculo = vehiculoIdVehiculo;
    }
   
    public int getCatalogoIdCatalogo() {
        return this.catalogoIdCatalogo;
    }
    
    public void setCatalogoIdCatalogo(int catalogoIdCatalogo) {
        this.catalogoIdCatalogo = catalogoIdCatalogo;
    }
    public int getVehiculoIdVehiculo() {
        return this.vehiculoIdVehiculo;
    }
    
    public void setVehiculoIdVehiculo(int vehiculoIdVehiculo) {
        this.vehiculoIdVehiculo = vehiculoIdVehiculo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CatalogoHasVehiculoId) ) return false;
		 CatalogoHasVehiculoId castOther = ( CatalogoHasVehiculoId ) other; 
         
		 return (this.getCatalogoIdCatalogo()==castOther.getCatalogoIdCatalogo())
 && (this.getVehiculoIdVehiculo()==castOther.getVehiculoIdVehiculo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCatalogoIdCatalogo();
         result = 37 * result + this.getVehiculoIdVehiculo();
         return result;
   }   


}


