package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * Impuesto generated by hbm2java
 */
public class Impuesto  implements java.io.Serializable {


     private Integer idImpuesto;
     private int paisIdPais;
     private String nombre;
     private String porcentaje;

    public Impuesto() {
    }

    public Impuesto(int paisIdPais, String nombre, String porcentaje) {
       this.paisIdPais = paisIdPais;
       this.nombre = nombre;
       this.porcentaje = porcentaje;
    }
   
    public Integer getIdImpuesto() {
        return this.idImpuesto;
    }
    
    public void setIdImpuesto(Integer idImpuesto) {
        this.idImpuesto = idImpuesto;
    }
    public int getPaisIdPais() {
        return this.paisIdPais;
    }
    
    public void setPaisIdPais(int paisIdPais) {
        this.paisIdPais = paisIdPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(String porcentaje) {
        this.porcentaje = porcentaje;
    }




}


