package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * MedioDePago generated by hbm2java
 */
public class MedioDePago  implements java.io.Serializable {


     private Integer idMedioDePago;
     private String tipo;

    public MedioDePago() {
    }

    public MedioDePago(String tipo) {
       this.tipo = tipo;
    }
   
    public Integer getIdMedioDePago() {
        return this.idMedioDePago;
    }
    
    public void setIdMedioDePago(Integer idMedioDePago) {
        this.idMedioDePago = idMedioDePago;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


