package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * PedidoHasMedioDePagoId generated by hbm2java
 */
public class PedidoHasMedioDePagoId  implements java.io.Serializable {


     private int pedidoIdPedido;
     private int medioDePagoIdMedioDePago;

    public PedidoHasMedioDePagoId() {
    }

    public PedidoHasMedioDePagoId(int pedidoIdPedido, int medioDePagoIdMedioDePago) {
       this.pedidoIdPedido = pedidoIdPedido;
       this.medioDePagoIdMedioDePago = medioDePagoIdMedioDePago;
    }
   
    public int getPedidoIdPedido() {
        return this.pedidoIdPedido;
    }
    
    public void setPedidoIdPedido(int pedidoIdPedido) {
        this.pedidoIdPedido = pedidoIdPedido;
    }
    public int getMedioDePagoIdMedioDePago() {
        return this.medioDePagoIdMedioDePago;
    }
    
    public void setMedioDePagoIdMedioDePago(int medioDePagoIdMedioDePago) {
        this.medioDePagoIdMedioDePago = medioDePagoIdMedioDePago;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedidoHasMedioDePagoId) ) return false;
		 PedidoHasMedioDePagoId castOther = ( PedidoHasMedioDePagoId ) other; 
         
		 return (this.getPedidoIdPedido()==castOther.getPedidoIdPedido())
 && (this.getMedioDePagoIdMedioDePago()==castOther.getMedioDePagoIdMedioDePago());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPedidoIdPedido();
         result = 37 * result + this.getMedioDePagoIdMedioDePago();
         return result;
   }   


}


