package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * PedidoHasMedioDePago generated by hbm2java
 */
public class PedidoHasMedioDePago  implements java.io.Serializable {


     private PedidoHasMedioDePagoId id;

    public PedidoHasMedioDePago() {
    }

    public PedidoHasMedioDePago(PedidoHasMedioDePagoId id) {
       this.id = id;
    }
   
    public PedidoHasMedioDePagoId getId() {
        return this.id;
    }
    
    public void setId(PedidoHasMedioDePagoId id) {
        this.id = id;
    }




}


