package Pojo;
// Generated 14/11/2017 11:12:28 AM by Hibernate Tools 4.3.1



/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private int idVehiculo;
     private String marca;
     private String modelo;
     private int año;
     private int precio;
     private int productoIdProducto;
     private String imagenV;
     private String imagenV_Nom;        
             

    public Vehiculo() {
    }

    public Vehiculo(int idVehiculo, String marca, String modelo, int año, int precio, int productoIdProducto, String imagenV, String imagenV_Nom) {
        this.idVehiculo = idVehiculo;
        this.marca = marca;
        this.modelo = modelo;
        this.año = año;
        this.precio = precio;
        this.productoIdProducto = productoIdProducto;
        this.imagenV = imagenV;
        this.imagenV_Nom = imagenV_Nom;
    }

    public int getIdVehiculo() {
        return idVehiculo;
    }

    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public int getAño() {
        return año;
    }

    public void setAño(int año) {
        this.año = año;
    }

    public int getPrecio() {
        return precio;
    }

    public void setPrecio(int precio) {
        this.precio = precio;
    }

    public int getProductoIdProducto() {
        return productoIdProducto;
    }

    public void setProductoIdProducto(int productoIdProducto) {
        this.productoIdProducto = productoIdProducto;
    }

    public String getImagenV() {
        return imagenV;
    }

    public void setImagenV(String imagenV) {
        this.imagenV = imagenV;
    }

    public String getImagenV_Nom() {
        return imagenV_Nom;
    }

    public void setImagenV_Nom(String imagenV_Nom) {
        this.imagenV_Nom = imagenV_Nom;
    }

    
}


